export const buttons = [
    [{ru: 'ё', en: '`', code: 'Backquote', letter: 'letter', shftE: 'shftE', shftEn: '~'}, 
    {ru: '1', en: '1', code: 'Digit1', shftE: 'shftE', shftEn: '!', shftR: 'shftR', shftRu: '!'}, 
    {ru: '2', en: '2', code: 'Digit2', shftE: 'shftE', shftEn: '@', shftR: 'shftR', shftRu: '"'}, 
    {ru: '3', en: '3', code: 'Digit3', shftE: 'shftE', shftEn: '#', shftR: 'shftR', shftRu: '№'}, 
    {ru: '4', en: '4', code: 'Digit4', shftE: 'shftE', shftEn: '$', shftR: 'shftR', shftRu: ';'}, 
    {ru: '5', en: '5', code: 'Digit5', shftE: 'shftE', shftEn: '%', shftR: 'shftR', shftRu: '%'}, 
    {ru: '6', en: '6', code: 'Digit6', shftE: 'shftE', shftEn: '^', shftR: 'shftR', shftRu: ':'}, 
    {ru: '7', en: '7', code: 'Digit7', shftE: 'shftE', shftEn: '&', shftR: 'shftR', shftRu: '?'}, 
    {ru: '8', en: '8', code: 'Digit8', shftE: 'shftE', shftEn: '*', shftR: 'shftR', shftRu: '*'}, 
    {ru: '9', en: '9', code: 'Digit9', shftE: 'shftE', shftEn: '(', shftR: 'shftR', shftRu: '('}, 
    {ru: '0', en: '0', code: 'Digit0', shftE: 'shftE', shftEn: ')', shftR: 'shftR', shftRu: ')'}, 
    {ru:'-', en: '-', code: 'Minus', shftE: 'shftE', shftEn: '_', shftR: 'shftR', shftRu: '_'}, 
    {ru:'=', en: '=', code: 'Equal', shftE: 'shftE', shftEn: '+', shftR: 'shftR', shftRu: '+'}, 
    {ru: 'Backspace', en: 'Backspace', code: 'Backspace'}],

    [{ru: 'Tab', en: 'Tab', code: 'Tab'}, 
    {ru: 'й', en: 'q', code: 'KeyQ', letter: 'letter'}, 
    {ru: 'ц', en: 'w', code: 'KeyW', letter: 'letter'}, 
    {ru: 'у', en: 'e', code: 'KeyE', letter: 'letter'}, 
    {ru: 'к', en: 'r', code: 'KeyR', letter: 'letter'}, 
    {ru: 'е', en: 't', code: 'KeyT', letter: 'letter'}, 
    {ru: 'н', en: 'y', code: 'KeyY', letter: 'letter'}, 
    {ru: 'г', en: 'u', code: 'KeyU', letter: 'letter'}, 
    {ru: 'ш', en: 'i', code: 'KeyI', letter: 'letter'}, 
    {ru: 'щ', en: 'o', code: 'KeyO', letter: 'letter'}, 
    {ru: 'з', en: 'p', code: 'KeyP', letter: 'letter'}, 
    {ru: 'х', en: '[', code: 'BracketLeft', letter: 'letter', shftE: 'shftE', shftEn: '{'}, 
    {ru: 'ъ', en: ']', code: 'BracketRight', letter: 'letter', shftE: 'shftE', shftEn: '}'}, 
    {ru: '\\', en: '\\', code: 'Backslash', shftE: 'shftE', shftEn: '|', shftR: 'shftR', shftRu: '\/'}, 
    {ru: 'Del', en: 'Del', code: 'Delete'}],

    [{ru: 'Caps Lock', en: 'Caps Lock', code: 'CapsLock'}, 
    {ru: 'ф', en: 'a', code: 'KeyA', letter: 'letter'}, 
    {ru: 'ы', en: 's', code: 'KeyS', letter: 'letter'}, 
    {ru: 'в', en: 'd', code: 'KeyD', letter: 'letter'}, 
    {ru: 'а', en: 'f', code: 'KeyF', letter: 'letter'}, 
    {ru: 'п', en: 'g', code: 'KeyG', letter: 'letter'}, 
    {ru: 'р', en: 'h', code: 'KeyH', letter: 'letter'}, 
    {ru: 'о', en: 'j', code: 'KeyJ', letter: 'letter'}, 
    {ru: 'л', en: 'k', code: 'KeyK', letter: 'letter'} , 
    {ru: 'д', en: 'l', code: 'KeyL', letter: 'letter'}, 
    {ru: 'ж', en: ';', code: 'Semicolon', letter: 'letter', shftE: 'shftE', shftEn: ':'}, 
    {ru: 'э', en: "'", code: 'Quote', letter: 'letter', shftE: 'shftE', shftEn: '"'}, 
    {ru: 'Enter', en: 'Enter', code: 'Enter'}],

    [{ru:'Shift Left', en:'Shift Left', code: 'ShiftLeft'}, 
    {ru: 'я', en: 'z', code: 'KeyZ', letter: 'letter'}, 
    {ru: 'ч', en: 'x', code: 'KeyX', letter: 'letter'}, 
    {ru: 'с', en: 'c', code: 'KeyC', letter: 'letter'}, 
    {ru: 'м', en: 'v', code: 'KeyV', letter: 'letter'}, 
    {ru: 'и', en: 'b', code: 'KeyB', letter: 'letter'}, 
    {ru: 'т', en: 'n', code: 'KeyN', letter: 'letter'},
    {ru: 'ь', en: 'm', code: 'KeyM', letter: 'letter'}, 
    {ru: 'б', en: ',', code: 'Comma', letter: 'letter', shftE: 'shftE', shftEn: '<'} , 
    {ru: 'ю', en: '.', code: 'Period', letter: 'letter', shftE: 'shftE', shftEn: '>'}, 
    {ru: '.', en: '\/', code: 'Slash', letter: 'letter', shftE: 'shftE', shftEn: '?',shftR: 'shftR', shftRu: ','}, 
    {ru:'Up', en: 'Up', code: 'ArrowUp'}, 
    {ru:'Shift Right', en:'Shift Right', code: 'ShiftRight'}],

    [{ru:'Ctrl', en: 'Ctrl', code: 'ControlLeft'}, 
    {ru:'Win', en: 'Win', code: 'MetaLeft'}, 
    {ru:'Alt', en: 'Alt', code: 'AltLeft'}, 
    {ru:'Space', en: 'Space', code: 'Space'}, 
    {ru:'Alt', en: 'Alt', code: 'AltRight'}, 
    {ru:'Left', en: 'Left', code: 'ArrowLeft'}, 
    {ru:'Down', en: 'Down', code: 'ArrowDown'}, 
    {ru:'Right', en: 'Right', code: 'ArrowRight'}, 
    {ru:'Ctrl', en: 'Ctrl', code: 'ControlRight'}],
]